### ISSUE TITLE
Cashe has been renamed

### ISSUE THREAD

**Issue by KartSriv** [KartSriv/K.I.T.T#7]
```
Traceback (most recent call last):
  File "kitt.py", line 198, in <module>
    FirstName,LastName,FullName,Name = NameEngine() # Name Engine
  File "kitt.py", line 92, in NameEngine
    Name = fileopen("UserData/name.txt")
  File "kitt.py", line 36, in fileopen
    Information = open(filename, "r")
IOError: [Errno 2] No such file or directory: 'UserData/name.txt'
```

**Comment by KartSriv** [comment]
Added All the lost cache files back to the repo
