### ISSUE TITLE
Random Bug

### ISSUE THREAD

**Issue by KartSriv** [KartSriv/K.I.T.T#8]
```
Traceback (most recent call last):
  File "kitt.py", line 202, in <module>
    location = weather.lookup_by_location('dublin') # Location
  File "/home/kartsriv/.local/lib/python2.7/site-packages/weather/weather.py", line 27, in lookup_by_location
    results = self._call(url)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/weather/weather.py", line 38, in _call
    req = requests.get(url)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/kartsriv/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='query.yahooapis.com', port=80): Max retries exceeded with url: /v1/public/yql?q=select*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text='dublin')%20and%20u='c'%20&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13ff91f8d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
```

**Comment by KartSriv** [comment]
Bypassed Weather Module 
`  File "/home/kartsriv/.local/lib/python2.7/site-packages/weather/weather.py", line 27, in lookup_by_location`
